### PR TITLE
ignore Oracle for maven tests

### PR DESCRIPTION
**Pull request by sdelamo**
https://ge.micronaut.io/s/gyuljzfugjef4

```
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: oracle/jdbc/OracleCommonPreparedStatement
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)		at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:583)		at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)		at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)		at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:265)		at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:94)
```

### CODE REVIEW

**Comment by graemerocher** [comment]
why was this done?

**Comment by alvarosanchez** [comment]
@sdelamo do we need to add `com.oracle.database.jdbc:ojdbc11` as a runtime dependency somewhere?

**Comment by sdelamo** [comment]
I did it to make the build pass. We need to investigate why. I don't know what is the the cause. We released a patch of SQL with: https://github.com/micronaut-projects/micronaut-sql/pull/1268

**Comment by sdelamo** [comment]
I will investigate this here: https://github.com/micronaut-projects/micronaut-starter/pull/2346 in case you want to collaborate.

**Pull request merged**
