### PR TITLE
Upgrading to Maven 3.9.0 for maven applications generated with Micronaut CLI/Launch

### LINKED ISSUE #1606: Consider using Maven 3.9.0 in maven applications generated with Micronaut CLI/Launch
https://maven.apache.org/docs/3.9.0/release-notes.html

### PR DESCRIPTION
**Pull request by wetted**
closes #1606

### CODE REVIEW

**Comment by wetted** [comment]
Note: I created the new wrapper files by creating a starter maven project and running: `mvnw wrapper:wrapper -Dmaven=3.9.0`

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
`MavenWrapperDownloader.java` needs to be removed

**Comment by wetted** [comment]
> `MavenWrapperDownloader.java` needs to be removed

Thanks, I'll do that. I was wondering about it.

**Comment by sdelamo** [comment]
ping @alvarosanchez

**Review by alvarosanchez — APPROVED** [review]

**Comment by sdelamo** [comment]
@wetted can you investigate the CI failure ?

**Comment by wetted** [comment]
> @wetted can you investigate the CI failure ?

@sdelamo there are some various issues around `CreateAwsLambdaCustomRuntimeSpec` I resolved part of it with a missing dependency on `micronaut-aws-ua`. There is still a kotest issue with version mismatches I need to resolve. I will raise a separate PR when I have it fixed.

**Comment by wetted** [comment]
ping @sdelamo this is good to go now

**Pull request merged**
