### PR TITLE
micronaut.core.version for micronaut-http-validation

### LINKED ISSUE #1968: micronaut.core.version for micronaut-http-validation
>  Heads up that it looks like micronaut-http-validation is using ${micronaut.version} in starter:
> 
> https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=MAVEN&test=JUNIT&features=data-jpa&features=micronaut-http-validation&version=4.0.0&activity=preview&showing=/pom.xml

It should use ${micronaut.core.version}

### PR DESCRIPTION
**Pull request by guillermocalvo**

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
It misses a test

**Comment by sdelamo** [comment]
I moved to 4.0.1 since it is a bug fix.

**Review by sdelamo — APPROVED** [review]
I prefer more functional tests than unit tests mocking.

**Comment by guillermocalvo** [comment]
> @sdelamo 
> I prefer more functional tests than unit tests mocking.

`BuildTestVerifier` doesn't support version number check, that's why I had to use a mock to verify that the dependency has the correct version.

I just pushed some changes to enhance `BuildTestVerifier` [here](https://github.com/micronaut-projects/micronaut-starter/pull/1975).

**Pull request merged**
