### PR TITLE
Add feature which generates a Gitlab-CI yaml file

### PR DESCRIPTION
**Pull request by juwit**
Hi :wave:

I saw that release 3.6.0 introduces new features that generates CI workflows.
This PR contributes generation of Gitlab-CI pipelines workflows for gradle and maven, with or without graalvm feature

Demos of generated projects can be found here:
* maven
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-maven-jdk11
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-maven-jdk17
* gradle
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-gradle-jdk11
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-gradle-jdk17

Generated pipeline looks like this :
image

and graalvm projects:
* maven
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-maven-graalvm-jdk11
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-maven-graalvm-jdk17
* gradle
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-gradle-graalvm-jdk11
  * https://gitlab.com/codekaio/test-micronaut-gitlab-ci-gradle-graalvm-jdk17

Generated pipeline for graalvm projects has an additional job:
image

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks! Perhaps could be updated to support native image. Similar to https://github.com/micronaut-projects/micronaut-starter/blob/3.6.x/starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/oci/templates/buildSpecGraal.rocker.raw

**Comment by juwit** [comment]
> Thanks! Perhaps could be updated to support native image. Similar to https://github.com/micronaut-projects/micronaut-starter/blob/3.6.x/starter-core/src/main/java/io/micronaut/starter/feature/ci/workflows/oci/templates/buildSpecGraal.rocker.raw

Great idea !  I'm starting to work on this !

**Comment by juwit** [comment]
I've added native-image builds for GraalVM-enabled projects.
I've also refactored the code to only use one rocker template.
And of course updated this PR description.

**Review by graemerocher — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]
Thanks!

**Pull request merged**
