### PR TITLE
test: GraalVM Logging test

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@msupic as expected the Graalvm test suite capture the error. Thus, I think we have a good check against logging and graalvm downstream as well.

**Comment by msupic** [comment]
@sdelamo - this is a different error. The tests should pass since the starter is using logback 1.4.8 at the moment. Let me fix this test and then we can test with the latest version of logback.

**Comment by msupic** [comment]
@sdelamo - [graalvm tests](https://github.com/micronaut-projects/micronaut-starter/actions/runs/6159910864) are ok now. If we upgrade only logback from 1.4.8 to 1.4.11 (without micronaut-core changes, actually without micronaut-context changes), the `LoggingTest` should fail when executed in a native image.

**Comment by sdelamo** [comment]
> @sdelamo - [graalvm tests](https://github.com/micronaut-projects/micronaut-starter/actions/runs/6159910864) are ok now. If we upgrade only logback from 1.4.8 to 1.4.11 (without micronaut-core changes, actually without micronaut-context changes), the `LoggingTest` should fail when executed in a native image.

I have removed the specified logback version https://github.com/micronaut-projects/micronaut-starter/pull/2044/commits/02f74c1c4b94b8df483f5fcd1fc08b424a6358f5

**Comment by msupic** [comment]
The version of logback is still 1.4.8
```
io.micronaut.platform:micronaut-platform:4.1.1-SNAPSHOT
    io.micronaut.logging:micronaut-logging-bom:1.1.1
        ch.qos.logback:logback-classic:1.4.8
        ch.qos.logback:logback-core:1.4.8
```

**Comment by sdelamo** [comment]
It should be 1.4.11 once platform snapshot updates since it contains logging 1.1.2

**Comment by msupic** [comment]
Yes. The logback version is 1.4.11 after micronaut-logging-bom version has been changed in the [micronaut platform](https://github.com/micronaut-projects/micronaut-platform/pull/917/files)

```
io.micronaut.platform:micronaut-platform:4.1.1-SNAPSHOT
    io.micronaut.logging:micronaut-logging-bom:1.1.2
        ch.qos.logback:logback-classic:1.4.11
        ch.qos.logback:logback-core:1.4.11
```
With this logback version and without [micronaut-core changes](https://github.com/micronaut-projects/micronaut-core/pull/9857/files), the `LoggingTest` should fail in a native image.

**Review by msupic — APPROVED** [review]

**Pull request merged**
