### PR TITLE
Mergeup 4.2.x

### PR DESCRIPTION
**Pull request by timyates**

### CODE REVIEW

**Comment by timyates** [comment]
I guess this is broken until https://github.com/micronaut-projects/micronaut-core/pull/10224 is merged...

I'm double checking...

[edit] confirmed...

**Comment by timyates** [comment]
@sdelamo The failing tests seem to be failing on the 4.3.x branch for some time...  Is it a known issue?

https://ge.micronaut.io/s/omy4bdbmehh46/tests/overview?outcome=FAILED

**Comment by radovanradic** [comment]
> @sdelamo The failing tests seem to be failing on the 4.3.x branch for some time... Is it a known issue?
> 
> https://ge.micronaut.io/s/omy4bdbmehh46/tests/overview?outcome=FAILED

Should probably change https://github.com/micronaut-projects/micronaut-starter/blob/4.3.x/starter-core/src/main/java/io/micronaut/starter/feature/database/HibernateReactiveFeature.java#L34
```
private static final String ORACLE_12C_DIALECT = "org.hibernate.dialect.Oracle12cDialect";
```
 to
```
private static final String ORACLE_DIALECT = "org.hibernate.dialect.OracleDialect";
```
Btw, this can be enabled too 
https://github.com/micronaut-projects/micronaut-starter/blob/4.3.x/test-features/src/test/groovy/io/micronaut/starter/core/test/feature/database/HibernateReactiveJpaSpec.groovy#L65
as Cedric fixed it while ago.

**Comment by timyates** [comment]
@radovanradic Cool...  Do we need a new dependency with that?

I made those changes locally locally, but I'm seeing

```
Message: java.lang.NoClassDefFoundError: oracle/jdbc/OracleCommonPreparedStatement
```

But only in the Maven test...

https://ge.micronaut.io/s/53qd77d2dqrsu/tests/overview?outcome=FAILED

**Comment by radovanradic** [comment]
> @radovanradic Cool... Do we need a new dependency with that?
> 
> I made those changes locally locally, but I'm seeing
> 
> ```
> Message: java.lang.NoClassDefFoundError: oracle/jdbc/OracleCommonPreparedStatement
> ```
> 
> But only in the Maven test...
> 
> https://ge.micronaut.io/s/53qd77d2dqrsu/tests/overview?outcome=FAILED

Looks like there is conflict in ojdbc8 dependency. Latest micronaut-sql uses 21.xxx and vertx 4.5.0. vertx expects 23.xxx and only in sql snapshot it was updated to 23.xx recently. When I changed dialect in config and just tried this locally 
```
generatorContext.getBuildProperties().put("micronaut.sql.version", "5.3.1-SNAPSHOT");
```
then build passed. So I guess we might need to release sql, update platform with that latest version and then this should work.

**Comment by timyates** [comment]
Sergio released sql-5.4.0 and it's just been included in the 4.3.0-SNAPSHOT of platform, so hopefully it will pass now :-)

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
