### PR TITLE
Adding projectGroupId to micronaut starter

### PR DESCRIPTION
**Pull request by YasserLahrach**
Adding projectGroupId to micronaut starter

### CODE REVIEW

**Comment by sdelamo** [comment]
why do we need this?

**Review by sdelamo — CHANGES_REQUESTED** [review]
[group id is `io.micronaut.starter`](https://github.com/micronaut-projects/micronaut-starter/blob/4.1.x/buildSrc/src/main/groovy/io.micronaut.internal.starter.base-module.gradle#L11). Why do we need this PR?

**Comment by YasserLahrach** [comment]
We use that variable to generate artifacts paths. so we had to use a workaround for micronaut starter project.

**Comment by YasserLahrach** [comment]
We use that variable to generate artifacts paths. We had to use a workaround for micronaut starter project.

**Comment by sdelamo** [comment]
why do you need to generate artifacts paths? What are you doing with starter?.

**Review by sdelamo — CHANGES_REQUESTED** [review]
We should not duplicate the project group definition https://github.com/micronaut-projects/micronaut-starter/blob/4.1.x/buildSrc/src/main/groovy/io.micronaut.internal.starter.base-module.gradle#L11

**Review by alvarosanchez — APPROVED** [review]

**Comment by sdelamo** [comment]
@YasserLahrach @alvarosanchez can you please comment on 

> why do you need to generate artifacts paths? What are you doing with starter?.

**Comment by alvarosanchez** [comment]
Starter is used for https://www.graal.cloud/gcn/launcher/

**Pull request merged**
