### PR TITLE
regression: Enable groovy tests

### PR DESCRIPTION
**Pull request by sdelamo**
We have a regression in groovy support from 4.1.2 to 4.1.3.

Core changes:

https://github.com/micronaut-projects/micronaut-core/compare/v4.1.6...v4.1.8

Starter changes: 

https://github.com/micronaut-projects/micronaut-starter/compare/v4.1.2...v4.1.3

 This PR reverts commit a53a2d7a3138a8795706a3d1ff0d5b5827047d35.

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you check this?

**Comment by sdelamo** [comment]
This is the error: 

```
> Task :compileJava NO-SOURCE
> Task :compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> io/micronaut/http/client/annotation/Client

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
1 actionable task: 1 executed

org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /var/folders/65/67w3r16d2cn0jmpygf_mgch80000gn/T/test-createcontroller-createcontrollergroovygradlejunitspec3735964372924414578 with arguments [test, --build-cache]

Output:
> Task :compileJava NO-SOURCE
> Task :compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> io/micronaut/http/client/annotation/Client

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
1 actionable task: 1 executed

	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:269)
	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:362)
	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:267)
	at app//io.micronaut.starter.test.CommandSpec.executeGradle(CommandSpec.groovy:86)
	at app//io.micronaut.starter.test.CommandSpec.executeBuild(CommandSpec.groovy:77)
	at io.micronaut.starter.cli.test.CreateControllerSpec.test creating a controller and running the test for #language and #testFramework and #buildTool(CreateControllerSpec.groovy:38)
```

**Comment by timyates** [comment]
Ok, it's caused by the addition of `compileOnly("io.micronaut:micronaut-http-validation")` to the Groovy build

This is then looking for `io.micronaut.http.client.annotation.Client` which isn't on the classpath when running `compileGroovy`

I suspect this is caused by https://github.com/micronaut-projects/micronaut-starter/pull/2084 but the actions passed there, so I'm currently unsure why

**Comment by sdelamo** [comment]
> Ok, it's caused by the addition of `compileOnly("io.micronaut:micronaut-http-validation")` to the Groovy build
> 
> This is then looking for `io.micronaut.http.client.annotation.Client` which isn't on the classpath when running `compileGroovy`
> 
> I suspect this is caused by #2084 but the actions passed there, so I'm currently unsure why


lets add Micronaut HTTP Client as a compile only validation as well with Micronaut HTTP validation.

I moved http client to testImplementation dependency unless you select it. 

We probably should create functionality to filter dependencies: 

if you have 

```
compileOnly("io.micronaut:micronaut-http-client")
implementation("io.micronaut:micronaut-http-client")
testImplementation("io.micronaut:micronaut-http-client")
```

filter:

```
implementation("io.micronaut:micronaut-http-client")
```

If you have:

```
compileOnly("io.micronaut:micronaut-http-client")
testImplementation("io.micronaut:micronaut-http-client")
```

filter:

```
compileOnly("io.micronaut:micronaut-http-client")
testImplementation("io.micronaut:micronaut-http-client")
```

**Comment by timyates** [comment]
K8s failures now 😥

**Comment by timyates** [comment]
Ok, so since the addition of http-validation and the moving of http-client to test, we required adding http-client as a compileOnly dependency for Gradle and Groovy, and adding discovery-core as a provided dependency for Maven/Groovy Kubernetes client projects

**Pull request merged**
