### PR TITLE
Add a new command to create an application builder style

### PR DESCRIPTION
**Pull request by jameskleeh**
render1650906677632

This is a little outdated now because I added a blue `> ` prompt where users enter the selection

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Review by sdelamo — COMMENTED** [review]
Tab autocomplete does not work for me. Am I testing it wrong?

AutocompleteBroken

**Comment by sdelamo** [comment]
It seems if I execute `java -jar starter-cli/build/libs/micronaut-cli-3.5.0-SNAPSHOT-all.jar create`. Tab automcompletion works. It works also for native image.

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
I have tested with native image as well. It work well with MacOS. Not sure if the Ansi logic will give any issues with Windows.

**Comment by sdelamo** [comment]
Scott De Vaughn tested it in in Windows as well. It works both the native and jar. 

Thanks @jameskleeh
For me this is going to be a time saver.

**Pull request merged**
