### PR TITLE
Upgrade to the build plugins 5.1.1

### PR DESCRIPTION
**Pull request by melix**
This PR is a build cleanup, making it possible to upgrade to the latest build plugins, leveraging the build cache. Apparently works fine but I'll do some more sanity checks before removing the draft status.

### CODE REVIEW

**Comment by melix** [comment]
@jameskleeh do you plan to review this one?

**Comment by jameskleeh** [comment]
> @jameskleeh do you plan to review this one?

Yes. Can you detail the steps you took to verify it behaves the same as before?

**Comment by melix** [comment]
I have checked the following:

- output of `./gradlew clean publishAllPublicationsToBuildRepository` is the same (in `build/repo`)
- output of `./gradlew clean docs` is the same

**Comment by jameskleeh** [comment]
@melix Did you compare against 3.2.x? The `build/repo` is not the same

**Comment by melix** [comment]
I did, yes, but maybe I did it wrong? Let me recheck.

**Comment by melix** [comment]
mmm indeed the 3.3.x version publishes more modules. I don't understand how I missed that, let me fix this.

**Pull request merged**
