### PR TITLE
Gradle plugin 4 3 6

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@melix @n0tl3ss This [change](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/979) broke the starter test. I changed it and it fixes for Java 17 but keeps failing for java 21. 
```
./gradlew :test-core:test --tests "io.micronaut.starter.core.test.GradleDockerConfigSpec.basic dockerfile creation"
```
[fix oraclecloud functions]](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/979) changed docker image not just for Oracle function but for lambda as well. Is that intentional? Can you look into this @n0tl3ss ?

**Comment by n0tl3ss** [comment]
> @melix @n0tl3ss This [change](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/979) broke the starter test. I changed it and it fixes for Java 17 but keeps failing for java 21.
> 
> ```
> ./gradlew :test-core:test --tests "io.micronaut.starter.core.test.GradleDockerConfigSpec.basic dockerfile creation"
> ```
> 
> [fix oraclecloud functions]]([micronaut-projects/micronaut-gradle-plugin#979](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/979)) changed docker image not just for Oracle function but for lambda as well. Is that intentional? Can you look into this @n0tl3ss ?

Hi @sdelamo, can you give me more explanation what exactly is failing for jdk 21?

**Comment by sdelamo** [comment]
> Hi @sdelamo, can you give me more explanation what exactly is failing for jdk 21?

Steps to reproduce: 

````
% sdk use java 21.0.2-amzn  
% ./gradlew :test-core:test --tests "io.micronaut.starter.core.test.GradleDockerConfigSpec.basic dockerfile creation"
````

https://ge.micronaut.io/s/p4ormb45za2pg

```
new File(dir, "build/docker/native-main/DockerfileNative").text.contains("FROM ghcr.io/graalvm/native-image-community:$javaVersion-ol9 AS graalvm")	
|        |                                                 |    |                                                      |	
|        |                                                 |    false                                                  17	
|        |                                                 FROM ghcr.io/graalvm/native-image-community:21-ol9 AS graalvm	
|        |                                                 WORKDIR /home/app	
|        |                                                 COPY --link layers/libs /home/app/libs	
|        |                                                 COPY --link layers/app /home/app/	
|        |                                                 COPY --link layers/resources /home/app/resources	
|        |                                                 RUN mkdir /home/app/config-dirs	
|        |                                                 RUN mkdir -p /home/app/config-dirs/generateResourcesConfigFile	
|        |                                                 RUN mkdir -p /home/app/config-dirs/io.netty/netty-common/4.1.80.Final	
|        |                                                 RUN mkdir -p /home/app/config-dirs/ch.qos.logback/logback-classic/1.4.9	
|        |                                                 COPY --link config-dirs/generateResourcesConfigFile /home/app/config-dirs/generateResourcesConfigFile	
|        |                                                 COPY --link config-dirs/io.netty/netty-common/4.1.80.Final /home/app/config-dirs/io.netty/netty-common/4.1.80.Final	
|        |                                                 COPY --link config-dirs/ch.qos.logback/logback-classic/1.4.9 /home/app/config-dirs/ch.qos.logback/logback-classic/1.4.9	
|        |                                                 RUN native-image --exclude-config .*/libs/netty-codec-http2-4.1.108.Final.jar ^/META-INF/native-image/.* --exclude-config .*/libs/netty-handler-4.1.108.Final.jar ^/META-INF/native-image/.* --exclude-config .*/libs/netty-buffer-4.1.108.Final.jar ^/META-INF/native-image/.* --exclude-config .*/libs/netty-common-4.1.108.Final.jar ^/META-INF/native-image/.* --exclude-config .*/libs/netty-transport-4.1.108.Final.jar ^/META-INF/native-image/.* --exclude-config .*/libs/netty-codec-http-4.1.108.Final.jar ^/META-INF/native-image/.* -cp /home/app/libs/*.jar:/home/app/resources:/home/app/application.jar --no-fallback -o application -H:ConfigurationFileDirectories=/home/app/config-dirs/generateResourcesConfigFile,/home/app/config-dirs/io.netty/netty-codec-http/4.1.80.Final,/home/app/config-dirs/io.netty/netty-common/4.1.80.Final,/home/app/config-dirs/io.netty/netty-buffer/4.1.80.Final,/home/app/config-dirs/io.netty/netty-transport/4.1.80.Final,/home/app/config-dirs/io.netty/netty-handler/4.1.80.Final,/home/app/config-dirs/io.netty/netty-codec-http2/4.1.80.Final,/home/app/config-dirs/ch.qos.logback/logback-classic/1.4.9 example.micronaut.Application	
|        |                                                 FROM cgr.dev/chainguard/wolfi-base:latest	
|        |                                                 EXPOSE 8080	
|        |                                                 COPY --link --from=graalvm /home/app/application /app/application	
|        |                                                 ENTRYPOINT ["/app/application"]
``

**Comment by sdelamo** [comment]
I separated the test in java 21 and java 17.

**Comment by n0tl3ss** [comment]
@sdelamo You are right this line affected it https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/b2f5685342e8fc7e08177cb0bbbbc5cc982a88cf/docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java#L62. 

Here is a conversation to version: https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/b2f5685342e8fc7e08177cb0bbbbc5cc982a88cf/docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java#L408

And it checks getToolchain version (machine jdk)? , it might be better to check traget source version?
https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/b2f5685342e8fc7e08177cb0bbbbc5cc982a88cf/docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java#L179

**Comment by sdelamo** [comment]
Not sure what we should do. I have merged this PR as I think it is fine but not sure if there is any issue with [#979](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/979).

**Pull request merged**
