### PR TITLE
feat: Add aws-lambda feature

### PR DESCRIPTION
**Pull request by sdelamo**
It adds a feature aws-lambda. This PR contains tests to verify the dependency for such feature is added.
see: https://github.com/micronaut-projects/micronaut-starter/issues/103

### CODE REVIEW

**Comment by graemerocher** [comment]
You will want to create an example function and test.. See the GCP/Azure HTTP examples

**Comment by sdelamo** [comment]
> You will want to create an example function and test.. See the GCP/Azure HTTP examples

Yes, this is just the dependency. I am splitting in separate PRs.

**Comment by graemerocher** [comment]
the less PRs the better, just group it into the one please

**Comment by sdelamo** [comment]
I will create it as a draft PR until I have everything.

**Pull request closed without merging**
