### PR TITLE
Added Micronaut Permissions feature

### PR DESCRIPTION
**Pull request by musketyr**
Added a new feature for [Micronaut Permissions](https://agorapulse.github.io/micronaut-permissions/)

I'm not sure about the integration test - it tests against every type of application as all the types are supported but this adds a significant time to the overall tests.

### CODE REVIEW

**Comment by sdelamo** [comment]
could you merge 3.5.x into this branch?

**Comment by musketyr** [comment]
@sdelamo done

**Comment by sdelamo** [comment]
can you merge 3.6.x into this branch?

**Comment by musketyr** [comment]
done, but I will have to start new PR against `3.6.x` right @sdelamo?

**Comment by musketyr** [comment]
nvm, I have found how to change the base :-D

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
