### PR TITLE
Maven wrapper to 3.9.1

### LINKED ISSUE #1693: Update to Maven 3.9.1
https://maven.apache.org/docs/3.9.1/release-notes.html

https://github.com/micronaut-projects/micronaut-starter/pull/1617/files

### PR DESCRIPTION
**Pull request by wetted**
closes #1693 

This PR also deletes `mvnw.bat.` Maven doesn't create such a file for the wrapper. If you run `mvn wrapper:wrapper -Dmaven=3.9.1` that results in a `mvnw` file, and a `mvnw.cmd` file for windows. It does not create a `mvnw.bat` file. 

The `Maven` feature ignores the `mvnw.bat` file that was under `:starter-core/srx/main/resources`. What it actually does is copy `mvnw.cmd` to `mvn.bat` in a generated project. I think we should stop doing that, make it consistent with the maven wrapper goal and generate the project with the `mvnw.cmd` file without changing the extension.

What do you think @alvarosanchez ?

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
There are 222 files changed. Please fix it.

**Comment by wetted** [comment]
> There are 222 files changed. Please fix it.

Oops...I had the wrong base branch. 🥴

**Review by sdelamo — COMMENTED** [review]
Have they removed `mvnw.bat` in maven 3.9.1?

**Comment by wetted** [comment]
> Have they removed `mvnw.bat` in maven 3.9.1?

Maven 3.9.1 does not have `mvn.bat` and maven wrapper does not have `mvnw.bat`. I think they've been gone longer than that.

**Review by alvarosanchez — APPROVED** [review]

**Pull request merged**
