### PR TITLE
Update camunda feature to latest release

### PR DESCRIPTION
**Pull request by tobiasschaefer**
I'm the lead developer of the Micronaut Camunda Integration Project at https://github.com/camunda-community-hub/micronaut-camunda-bpm. Please merge this PR.

### CODE REVIEW

**Comment by ilopmar** [comment]
This should target branch `3.2.x`

**Comment by tobiasschaefer** [comment]
Hi @ilopmar ,

thanks for looking into this PR.

Should this target 3.2.x because our dependency update is a minor update, not only patch?

If so: I'd appreciate it, if you wouldn't look too closely on the semantic version numbers. As an open source project with limited resources and not fully integrated into the Micronaut Release process we would always be on step behind if you don't merge it. That would from my point of view not be the best experience for the user. This pull request will definitely not break anything.

A similar pull request was merged in #941 and I'd really appreciate if you could merge this one too.

When will 3.2x be released?

**Comment by ilopmar** [comment]
This is what we follow regarding versioning in modules and include it in core's BOM: https://github.com/micronaut-projects/micronaut-core/wiki/Module-Upgrade-Strategy

Giving it a second look I've realized that the micronaut-camunda module is not in our BOM. So this new version upgrade would only affect to new users creating applications with Launch.
I'm going to merge the PR.

3.2.0 will be release before the end on November.

**Review by ilopmar — APPROVED** [review]

**Comment by tobiasschaefer** [comment]
Thanks @ilopmar 

Yes, this only affects newly created applications - we're not listed in the BOM.

**Pull request merged**
