### PR TITLE
Remove deprecated action set-output usage

### LINKED ISSUE #1604: remove deprecated set-output and save-state
and https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by timyates**
This project is not updated by the template project, so it is done here.

Fixes #1604

Done on the 3.8.x branch

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
why the CI failures ? @timyates

**Comment by timyates** [comment]
Not sure...investigating

**Comment by timyates** [comment]
> Could not find io.micronaut:micronaut-bom:3.8.5-SNAPSHOT.

🤔

**Comment by sdelamo** [comment]
> > Could not find io.micronaut:micronaut-bom:3.8.5-SNAPSHOT.
> 
> 🤔

Let me trigger manually a snapshot publication.

**Comment by timyates** [comment]
Java CI failed as it couldn't get the baseline (probably due to api limits) 🙄

**Comment by timyates** [comment]
Rerunning as https://github.com/micronaut-projects/micronaut-core/actions/runs/4125042369 passed

**Comment by timyates** [comment]
I have no idea what the error is...

For some reason it's failing to generate rocker template source https://ge.micronaut.io/s/xjxbjjrwagzui

But why now?

**Comment by timyates** [comment]
Ok, it's caused by 8dfad71edd7517ff6bcdee57027cdb645c23cc0d (Micronaut Build Plugins 5.4.5)

@melix @sdelamo can you think of a reason why?  Did Antlr change somehow?

**Comment by melix** [comment]
Doesn't ring a bell, but it may be that a dependency which was accidentally on classpath before disappeared...

**Comment by timyates** [comment]
I suspect https://ge.micronaut.io/c/7wbsn5d2z77mi/owfqqtgmt7wns/build-dependencies#dependency:::settings.gradle:org.antlr:antlr4-runtime:4.8-1 might be causing issues with Rocker, but I have no proof 🤔

**Comment by timyates** [comment]
@melix Ok, I have downgraded the settings plugin to 5.3.18 which I suspect will pass

From my investigations, it seems that tomlj 1.1.1 is pulling [in a much newer version of antlr](https://ge.micronaut.io/s/owfqqtgmt7wns/build-dependencies?focusedDependency=WzAsMCwxNDcsWzAsMCxbMCwxLDIyLDE0N11dXQ&toggled=W1swXSxbMCwwXSxbMCwwLFswXV0sWzAsMCxbMCwxXV0sWzAsMCxbMCwxLDNdXSxbMCwwLFswLDEsMywzM11dLFswLDAsWzAsMSwzLDMzLDQwXV0sWzAsMCxbMCwxLDIyXV1d) and Rocker is built against "4.5.3"

I'm guessing antlr doesn't follow semver but the [version of antlr we pulled in previously with tomlj 1.0.0](https://ge.micronaut.io/s/476g7tk3temnm/build-dependencies?focusedDependency=WzAsMCwxNDcsWzAsMCxbMCwxLDIxLDE0N11dXQ&toggled=W1swXSxbMCwwXSxbMCwwLFswXV0sWzAsMCxbMCwxXV0sWzAsMCxbMCwxLDIxXV1d) seems to work (but outputs a warning) "_ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.8_"

**Comment by timyates** [comment]
And now it looks like bintray is having issues 😢

**Comment by melix** [comment]
Indeed, it looks like the accidental upgrade of Antlr is the culprit. Would there be a newer version of rocker which would fix this issue?

**Comment by sdelamo** [comment]
> Indeed, it looks like the accidental upgrade of Antlr is the culprit. Would there be a newer version of rocker which would fix this issue?

I can try to send them a PR. 

Could we exclude the version pulled from toml to workaround? We should be able to use the latest version of build plugins.

**Comment by timyates** [comment]
> Could we exclude the version pulled from toml

Or try downgrading it somehow here

**Comment by sdelamo** [comment]
> I can try to send them a PR.

I tried updating the `antlr.version` to `4.8-1`

https://github.com/fizzed/rocker/blob/master/pom.xml#L23

and it fails. Thus, I don't think it is an easy upgrade for Rocker.

**Comment by melix** [comment]
I gave a try at downgrading tomlj:

```gradle

buildscript {
    dependencies {
        classpath 'org.tomlj:tomlj:1.0.0!!'
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '5.4.5'
}
```

It works, but antlr is still upgraded by _checkstyle_: https://ge.micronaut.io/s/vttt7igaizbbg/build-dependencies?dependencies=antlr&expandAll&focusedDependency=WzAsMCwxNDYsWzAsMCxbMV1dXQ&focusedDependencyView=versions

So I tried to downgrade antlr instead:

```gradle
buildscript {
    dependencies {
        classpath 'org.antlr:antlr4-runtime:4.7.2!!'
    }
}
```

This seem to work: https://ge.micronaut.io/s/oxgh2znsjdthi/build-dependencies?dependencies=antlr&expandAll even if I use checkstyle: https://ge.micronaut.io/s/r2wsisxpf4jay

**Comment by timyates** [comment]
I have a PR for Rocker that works with 4.11.1 (I think)

**Comment by timyates** [comment]
~~https://github.com/fizzed/rocker/pull/168~~

**Comment by timyates** [comment]
Ignore me...  Forgot to run with java 8...  Antlr 4.11.1 requires java 11 🙄

**Comment by timyates** [comment]
Pushed the version lock for antlr here https://github.com/micronaut-projects/micronaut-starter/pull/1605/commits/7525769dd3a37bf1ed14aba227263868f45f09c1

Lets see

**Comment by timyates** [comment]
@sdelamo Green!

**Comment by sdelamo** [comment]
@melix and @timyates thanks for the fix and investigation.

**Pull request merged**
