### PR TITLE
feat: apply gradle java-library plugin when not app

### PR DESCRIPTION
**Pull request by sdelamo**
When we don't apply the `application` Gradle plugin, I think when should apply the `java-library`

### CODE REVIEW

**Comment by graemerocher** [comment]
I don't think we can assume that can we? Functions, messaging, CLI apps are not apps either

**Comment by sdelamo** [comment]
But for functions. I want `java-library` applied. Don't I want it for other apps?. I mean we need to tell that the build contains java sources.

**Comment by sdelamo** [comment]
For Kotlin, when we don't apply `application` gradle plugin we should apply the java plugin `id "java"` for groovy and java we can use `id "java-library"`

**Comment by graemerocher** [comment]
A function is not a library, why would you want it applied?

**Comment by graemerocher** [comment]
Unless you mean the "java" plugin which is not the same as "java-library"

**Pull request closed without merging**
