### PR TITLE
fix: Use more appropriate default memory setting for lambda

### PR DESCRIPTION
**Pull request by sdelamo**
Close #927
See https://github.com/micronaut-projects/micronaut-aws/issues/762

This allows to simplify custom features in guides. See discussion: https://github.com/micronaut-projects/micronaut-guides/pull/557#discussion_r721137951

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]
Looks ok to me but maybe @jameskleeh should have another look

**Comment by graemerocher** [comment]
@jameskleeh can we merge this?

**Comment by jameskleeh** [comment]
@graemerocher Yeah as soon as the build passes

**Comment by sdelamo** [comment]
Unrelated to this change but in order to fulfil the tests, I had to order the kotlin gradle plugins before the micronaut gradle library plugin. 

For a function this does not work: 

```
plugins {
    ....
    id("org.jetbrains.kotlin.kapt") version "1.5.21"
    id("io.micronaut.library") version "2.0.8"
}
```

However, this works:

```
plugins {
    ....
    id("io.micronaut.library") version "2.0.8"
    id("org.jetbrains.kotlin.kapt") version "1.5.21"}
```

**Comment by sdelamo** [comment]
16 status is not reported but the build is green @jameskleeh

**Pull request merged**
