### PR TITLE
implement support for toml array tables

### PR DESCRIPTION
**Pull request by yawkat**
Also has some build changes

### CODE REVIEW

**Review by melix — APPROVED** [review]

**Review by sdelamo — CHANGES_REQUESTED** [review]
This PR should target 3.9.x

**Comment by yawkat** [comment]
@sdelamo it's not required for starter (we don't really produce arrays) and i want to use records

**Comment by sdelamo** [comment]
> @sdelamo it's not required for starter (we don't really produce arrays) and i want to use records

why are we adding it to starter if we don't need it?

**Comment by yawkat** [comment]
so that we don't have diverging code between starter and build

**Comment by sdelamo** [comment]
@yawkat closing this for now.

**Pull request closed without merging**
