### PR TITLE
add jdbc-ucp feature support

### PR DESCRIPTION
**Pull request by recursivecodes**
add support for jdbc-ucp 💯

### CODE REVIEW

**Comment by jameskleeh** [comment]
This needs tests similar to the other jdbc features

**Comment by recursivecodes** [comment]
Sorry @jameskleeh - i'm not seeing any tests for the other jdbc-x features. Can you point me to them?

**Comment by recursivecodes** [comment]
Won't this be covered already under the JdbcFeature.spec? It seems like it dynamically tests all of them...

**Comment by jameskleeh** [comment]
@recursivecodes My fault - It's actually already covered with https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-core/src/test/groovy/io/micronaut/starter/feature/database/jdbc/JdbcSpec.groovy

**Comment by recursivecodes** [comment]
That's what I thought, thanks.

**Comment by jameskleeh** [comment]
Thanks for the contribution

**Pull request merged**
