### PR TITLE
Upgrade to Micronaut Gradle plugin 3.6.0

### PR DESCRIPTION
**Pull request by melix**

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
I have upgraded the Graal tests applications 

`./upgrade-gradle-plugin-version.sh 3.7.x 3.5.3 3.6.0`

**Comment by sdelamo** [comment]
@timyates can you look into the failures? There seems some classes are not found.

**Comment by timyates** [comment]
There are multiple issues here, but they all exist on 3.7.x and are not related to this PR

One is that commons-io is not on the classpath for 3.7 any more (not sure why currently)

Another is that we seem to be missing some CloudWatch classes

```
  Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.cloudwatchlogs.CloudWatchLogsClientBuilder
```

And the third is that native-image is broken by https://github.com/micronaut-projects/micronaut-core/issues/8012

**Comment by timyates** [comment]
Commons io and cloudwatch investigation is here https://github.com/micronaut-projects/micronaut-starter/pull/1419

**Review by timyates — APPROVED** [review]

**Comment by sdelamo** [comment]
[Mockk had a regression in 1.2.7 which made the library JDK 11 only](https://github.com/mockk/mockk/issues/898). It seems to be fixed in 1.2.8. I am releasing a new version of Micronaut Test. :-[

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-starter/pull/1422

**Pull request closed without merging**
