### PR TITLE
#499 puts the MacPorts installation docs back in

### PR DESCRIPTION
**Pull request by willbuck**

### CODE REVIEW

**Comment by willbuck** [comment]
Confirmed these directions work on Mac today, not sure what the CI failure was looked like an unrelated error though

**Comment by graemerocher** [comment]
Do we publish to macports?

**Comment by willbuck** [comment]
I am not 100% certain on it @graemerocher, but it would seem to be the case that we do; the version I installed successfully via this method was 2.1.1

Hope all is well with you!

**Comment by alvarosanchez** [comment]
The Micronaut port file is kindly supported by @breun.

**Comment by breun** [comment]
I indeed maintain the Portfile for Micronaut in MacPorts: https://github.com/macports/macports-ports/blob/master/java/micronaut/Portfile

**Review by JasonTypesCodes — APPROVED** [review]

**Pull request merged**
