### PR TITLE
Gradle 7.6.1

### LINKED ISSUE #1551: Upgrade to Gradle 7.6
We have to do it in two places:  https://github.com/micronaut-projects/micronaut-starter/pull/1373/files

### PR DESCRIPTION
**Pull request by timyates**

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
There should be 8 files changed. 4 in root project itself, 4 in `starter-core/src/main/resources/gradle`

**Comment by timyates** [comment]
Also `HibernateReactiveJpaSpec` seems to be hanging... Maybe related

**Review by sdelamo — APPROVED** [review]

**Comment by timyates** [comment]
Right...it's the Oracle test that's hanging...

Investigating on an x86 machine where the image works...

**Comment by timyates** [comment]
So both Maven and Gradle hang when doing the oracle feature test for Hibernate Reactive JPA... 

I am currently stumped as to why...

**Pull request merged**
