### PR TITLE
Convert JdkVersion from enum to class

### PR DESCRIPTION
**Pull request by burtbeckwith**
Changing from an enum allows adding new instances via the constructor (e.g. when using starter as a library) without recompiling.

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
Please, change the PR base to 4.3.x

**Comment by burtbeckwith** [comment]
@sdelamo ok to merge?

**Review by sdelamo — CHANGES_REQUESTED** [review]
Can we do this change in a backwards compatible way so that the JSON serialization remains? See test: https://github.com/micronaut-projects/micronaut-starter/pull/2192/commits/7faa53597a0eaa8aff35da3fdd2bddcd80a62d71

**Comment by sdelamo** [comment]
> Can we do this change in a backwards compatible way so that the JSON serialization remains? See test: [7faa535](https://github.com/micronaut-projects/micronaut-starter/commit/7faa53597a0eaa8aff35da3fdd2bddcd80a62d71)

I tried annotating JdkVersion::name with `@JsonValue` but that breaks `SelectOptionsControllerTest` test.

**Comment by sdelamo** [comment]
I created a issue for a bug in serde which affects this PR https://github.com/micronaut-projects/micronaut-serialization/pull/709

**Pull request merged**
