### PR TITLE
Split k8s yaml from kubernetes config feature. Fixes #355

### LINKED ISSUE #355: Generate basic k8s service config when selecting kubernetes feature
We should generate a basic k8s config when creating an app with the `kubernetes` feature.

### PR DESCRIPTION
**Pull request by graemerocher**
Fixes #355

### CODE REVIEW

**Comment by graemerocher** [comment]
Requires #354 to be merged first

**Comment by graemerocher** [comment]
Nothing, it is just out of the box applications with Micronaut + `--features kubernetes` fail with health check problems due to the endpoints being forbidden on OKE (oracle's kubernetes) which is a bad user experience.

It probably requires extra permissions and setup to get working. Config watch and distributed config support is a very specific use case and doesn't need to to the default so I think a split of `kubernetes` and `config-kubernetes` make sense.

**Comment by alvarosanchez** [comment]
Agreed on the split.

Regarding the permissions, it likely needs the ones described in https://micronaut-projects.github.io/micronaut-kubernetes/latest/guide/#_kubernetes_api_authentication

**Comment by graemerocher** [comment]
For some reason the checks are showing as not completed even though they are completed if you look at the `Actions` tab 🤔

**Pull request merged**
