### PR TITLE
Micronaut Console DSL Contribution by the Micronaut Worker feature

### PR DESCRIPTION
**Pull request by musketyr**
Micronaut Worker contributes to the Micronaut Console DSL. This change is the same as running the application and refreshing the DSL file manually after creating the application.

### CODE REVIEW

**Comment by sdelamo** [comment]
could you merge 3.5.x into this branch?

**Comment by musketyr** [comment]
@sdelamo done

**Comment by sdelamo** [comment]
can you merge 3.6.x into this branch?

**Comment by musketyr** [comment]
done

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
