### PR TITLE
give a new look to openapi

### PR DESCRIPTION
**Pull request by CtrlAltFly**
added ui theme as material

### CODE REVIEW

**Comment by sdelamo** [comment]
> added ui theme as material

@shekarroy15 is there any problem with the previous default cc @altro3

**Comment by altro3** [comment]
don't think there is problem. @shekarroy15  just wanted to change the default theme :-). Right?

**Comment by CtrlAltFly** [comment]
oh absolutely.. no problems seen. 
in a project i used this theme and it looks much cooler. so why not have it as default for folks who are going to use it hereafter was the thought. 
@sdelamo @altro3

**Comment by altro3** [comment]
In general, I don't see any problems with this. And some themes are actually made better than the default one.

**Pull request merged**
